### PR TITLE
Super important stuff

### PR DESCRIPTION
**Pull request by joshdorsey**
ping

### CODE REVIEW

**Comment by jdloft** [comment]
Sir, it looks like your pull request broke the CI. Ha lol.

**Comment by joshdorsey** [comment]
lol yeah I was talking to my friend when I submitted it and said something like "...oops, I kicked off a CI build.

...oops, it failed, but it doesn't look like it was my fault."

**Comment by joshdorsey** [comment]
Here's something amusing, I found a trello card about RAID on the ol' Message Bored and you (on top of the usual windows complaints) complained about software RAID.  It's funny because I've got a Windows RAID 5 thing goin on right now (don't worry I'm replacing it with a hardware RAID controller as soon as I can).  I really wish I'd known more about computers in high school.

**Comment by jdloft** [comment]
Uh huh. How 'bout them good ol' days. I certainly have learned more as well.

**Comment by joshdorsey** [comment]
in all seriousness, we should catch up

**Comment by jdloft** [comment]
Oh for sure. I sent you an email. :)

**Pull request closed without merging**
